version: '3'

services: 

  laravel:
    build:
      context: ./laravel-example
      dockerfile: Dockerfile.prod
    image: mcodex/laravel:prod
    container_name: laravel
    networks: 
      - laranet
  
  nginx:
    build:
      context: ./nginx-example
      dockerfile: Dockerfile.prod
    image: mcodex/nginx:prod
    container_name: nginx
    networks: 
      - laranet
    ports: 
      - "8080:80"

networks: 
  laranet:
    driver: bridge
