FROM node:15-alpine as builder

WORKDIR /usr/src/app

COPY . .

RUN yarn global add @nestjs/cli && \
    yarn && \
    yarn build

FROM node:15-alpine

ENV DOCKERIZE_VERSION v0.6.1

RUN apk add --no-cache openssl

RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

COPY --from=builder /usr/src/app/ .

RUN rm -rf node_modules yarn.lock && \
    yarn --production

EXPOSE 3000
