version: '3'

services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: yarn start:prod
    networks: 
      - node-network
    ports: 
      - "3000:3000"
    depends_on: 
      - db
      
  nginx:
    build:
      context: .docker/nginx
    container_name: nginx  
    # entrypoint: dockerize -wait http://app:3000 -timeout 20s /docker-entrypoint.sh
    # command: "nginx -g daemon off;"
    ports: 
      - "8080:3000"  
    networks: 
      - node-network
    depends_on: 
      - app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    volumes: 
      - ./.docker/dbdata:/var/lib/mysql
    # ports: 
    #   - "3306:3306"      
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge


